{
    'name': 'Campus HR / Organisasi',
    'version': '19.0.3.0.0',
    'summary': 'Extension module: Organisasi Mahasiswa, Proposal Kegiatan, Kepanitiaan',
    'category': 'Education',
    'author': 'Reyhan',
    'depends': ['campus_core'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/campus_hr_data.xml',
        'report/proposal_report.xml',
        'views/organisasi_views.xml',
        'views/master_data_views.xml',
        'views/proposal_views.xml',
        'views/mahasiswa_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
